[logging]

[logging.console]
enabled = true
colored = true
level = "INFO"
format = "%(asctime)s - %(levelname)-8s - %(name)s - %(message)s"

[logging.file]
enabled = true
level = "INFO"
format = "%(asctime)s - %(levelname)-8s - %(name)s - %(message)s"
path = "jentic_agents/logs/standard_agent.log"
file_rotation = true
max_bytes = 10485760
backup_count = 5

[logging.libraries]
LiteLLM = "WARNING"
httpx = "WARNING"
httpcore = "WARNING"

[llm]
model = "gemini/gemini-2.5-flash" # Model names require a provider prefix (e.g., "<provider>/<model>")


