[logging]
console_enabled = true
file_enabled = false
colored = true
level = "DEBUG"
format = "%(asctime)s - %(levelname)-8s - %(name)s - %(message)s"
path = "jentic_agents/logs/standard_agent.log"

[llm]
provider = "gemini"
model = "gemini-2.5-flash"

